### ISSUE TITLE
No widgets visible when taxi.ipynb is published to dashboards server

### ISSUE THREAD

**Issue by rs2** [jupyter-incubator/declarativewidgets_explorer#74] opened 2016-08-24 11:20 UTC
The error in the console is: 

```
http://server:3000/dashboards/taxi/urth_components/declarativewidgets-explorer/urth-viz-explorer.html Failed to load resource: the server 
```
The URL above prints more:

```
Error: Error getting notebook info: C:\Users\rs2\AppData\Roaming\npm\node_modules\jupyter-dashboards-server\data\taxi\urth_components\declarativewidgets-explorer\urth-viz-explorer.html - ENOENT: no such file or directory, stat 'C:\Users\rs2\AppData\Roaming\npm\node_modules\jupyter-dashboards-server\data\taxi\urth_components\declarativewidgets-explorer\urth-viz-explorer.html'
    at _statError (C:\Users\rs2\AppData\Roaming\npm\node_modules\jupyter-dashboards-server\app\notebook-fs.js:39:13)
    at C:\Users\rs2\AppData\Roaming\npm\node_modules\jupyter-dashboards-server\app\notebook-fs.js:60:32
    at FSReqWrap.oncomplete (fs.js:117:15)
```

**Comment by dalogsdon** [comment] 2016-08-24 15:18
We haven't tested dashboard integration extensively yet (#9).

Are you able to publish other declarative widgets to the dashboard server?

**Comment by rs2** [comment] 2016-08-24 15:51
Affirmative.

**Comment by dalogsdon** [comment] 2016-08-30 22:37
I'm seeing some path issues when trying with the dashboards_setup project. I'm not yet sure if it is related to the error above.

**Comment by rs2** [comment] 2016-08-31 06:23
How do you recommend running/testing the widgets?

**Comment by dalogsdon** [comment] 2016-09-01 13:58
The easiest way is to use the [dashboards_setup](https://github.com/jupyter-incubator/dashboards_setup) project and use the `docker_deploy` folder. However, at the moment this does not support the `explore` function, but you can still use the [declarative example](https://github.com/jupyter-incubator/declarativewidgets_explorer/blob/master/notebooks/examples/urth-viz-explorer.ipynb) in the "urth viz query + explorer" section.

If you want to try out the `explore` function, you will need to use the `dev_deploy` folder and build the latest version of declarativewidgets. I was trying this the other day and noticed the `dev_deploy` README needs a few updates, so if you go that route you will need to examine the `Makefile` and `docker-compose.yml` file until the README is updated.

**Comment by dalogsdon** [comment] 2016-09-27 14:14
Declarative widgets 0.7.0 has been released. I was able to see the widget using `explore` in a deployed dashboard using the `docker_deploy` folder as described above. You will have to edit the `docker_deploy/docker-compose.yml` file to bump the `DECLWIDGETS_VER` to `'0.7.*'`.

Currently there is no support for explorer load state with dashboards.

**Comment by peller** [comment] 2016-09-27 14:45
see jupyter-incubator/dashboards_server#294

**Comment by dalogsdon** [comment] 2016-10-05 14:19
Closing since this can be done per my most recent comment above.

**Closed by dalogsdon** 2016-10-05 14:19 UTC

**Comment by pranavbahl2308** [comment] 2017-07-28 15:45
Facing the same problem:

Error: Error getting notebook info: /usr/local/lib/node_modules/jupyter-dashboards-server/data/api/kernels - ENOENT: no such file or directory, stat '/usr/local/lib/node_modules/jupyter-dashboards-server/data/api/kernels'
    at _statError (/usr/local/lib/node_modules/jupyter-dashboards-server/app/notebook-fs.js:39:13)
    at /usr/local/lib/node_modules/jupyter-dashboards-server/app/notebook-fs.js:60:32
    at FSReqWrap.oncomplete (fs.js:152:21)

**Comment by einarbmag** [comment] 2018-03-14 21:50
@pranavbahl2308 , did you ever figure out what was wrong in your case? I'm getting the exact same issue when trying out the dashboard-server using the PCF setup, and it seems clear to me that the problem is that there is an issue with paths, it looks in ".../jupyter-dashboards-server/data/api/kernels" instead of "/jupyter-dashboards-server/data/dashboards/MY_DASHBOARD_NAME".
